### ISSUE TITLE
Setting unknown property: updated_time 

### ISSUE THREAD

**Issue by srakl** [daxslab/yii2-taggedview#3]
How do i set the updated_time or disable it?

when i add `'updated_time' => '',` in my `main.php` i get this error

```
yii\base\UnknownPropertyException: Setting unknown property: daxslab\taggedview\View::updated_time 
```

**Comment by glpzzz** [comment]
`$updated_time` is private and the value is set from the public `$date` attribute. You should not use `updated_time` directly
